### ISSUE TITLE
We expect the `context` property of the webpack configuration above to be an absolute path.

### ISSUE THREAD

**Issue by hitmc** [reframejs/reframe-proto#1]
Im getting this error after yarn install and yarn dev.

`yarn run v1.17.3
warning package.json: No license field
$ goldpage dev ./server/start
Building****************************************
************* Stack Trace **************
****************************************
Error:
    at getCallStack (D:\vue-work\reframe-full-stack\node_modules\reassert\assert.js:170:27)
    at reassert (D:\vue-work\reframe-full-stack\node_modules\reassert\assert.js:25:21)
    at module.exports (D:\vue-work\reframe-full-stack\node_modules\reassert\usage.js:9:19)
    at source_entry_points.map.src_entry (D:\vue-work\reframe-full-stack\node_modules\@rebuild\build\compile.js:605:13)
    at Array.map (<anonymous>)
    at entries.forEach (D:\vue-work\reframe-full-stack\node_modules\@rebuild\build\compile.js:594:51)
    at Array.forEach (<anonymous>)
    at get_entries (D:\vue-work\reframe-full-stack\node_modules\@rebuild\build\compile.js:588:13)
    at get_entry_points (D:\vue-work\reframe-full-stack\node_modules\@rebuild\build\compile.js:542:5)
    at get_output_info (D:\vue-work\reframe-full-stack\node_modules\@rebuild\build\compile.js:399:42)
    at get_compilation_info (D:\vue-work\reframe-full-stack\node_modules\@rebuild\build\compile.js:381:9)
    at onCompileEnd.addListener (D:\vue-work\reframe-full-stack\node_modules\@rebuild\build\compile.js:129:28)
    at onCompileEndListeners.forEach.fn (D:\vue-work\reframe-full-stack\node_modules\@rebuild\build\compile.js:289:49)
    at Array.forEach (<anonymous>)
    at avoidErrorSwallowing (D:\vue-work\reframe-full-stack\node_modules\@rebuild\build\compile.js:289:35)
    at avoidErrorSwallowing (D:\vue-work\reframe-full-stack\node_modules\@rebuild\build\compile.js:718:9)
    at webpack_compiler.hooks.done.tap.webpack_stats (D:\vue-work\reframe-full-stack\node_modules\@rebuild\build\compile
.js:288:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\vue-work\reframe-full-stack\node_modules\tapable\lib\Hook
CodeFactory.js:33:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (D:\vue-work\reframe-full-stack\node_modules\tapable\lib\Hook.js:154:20)
    at Watching._done (D:\vue-work\reframe-full-stack\node_modules\webpack\lib\Watching.js:98:28)
    at compiler.emitRecords.err (D:\vue-work\reframe-full-stack\node_modules\webpack\lib\Watching.js:73:19)
    at Compiler.emitRecords (D:\vue-work\reframe-full-stack\node_modules\webpack\lib\Compiler.js:489:39)
    at compiler.emitAssets.err (D:\vue-work\reframe-full-stack\node_modules\webpack\lib\Watching.js:54:20)
    at hooks.afterEmit.callAsync.err (D:\vue-work\reframe-full-stack\node_modules\webpack\lib\Compiler.js:475:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\vue-work\reframe-full-stack\node_modules\tapable\lib\Hook
CodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (D:\vue-work\reframe-full-stack\node_modules\tapable\lib\Hook.js:154:20)
    at asyncLib.forEachLimit.err (D:\vue-work\reframe-full-stack\node_modules\webpack\lib\Compiler.js:472:27)
    at D:\vue-work\reframe-full-stack\node_modules\neo-async\async.js:2818:7
    at done (D:\vue-work\reframe-full-stack\node_modules\neo-async\async.js:3522:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\vue-work\reframe-full-stack\node_modules\tapable\lib\Hook
CodeFactory.js:33:10), <anonymous>:6:1)
    at outputFileSystem.writeFile.err (D:\vue-work\reframe-full-stack\node_modules\webpack\lib\Compiler.js:454:33)
    at D:\vue-work\reframe-full-stack\node_modules\graceful-fs\graceful-fs.js:57:14
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)

****************************************
************* Wrong Usage **************
****************************************
{
  "entry": {
    "main": [
      "D:\\vue-work\\reframe-full-stack\\pages\\main.page.js"
    ],
    "server": [
      "D:\\vue-work\\reframe-full-stack\\server\\start.js"
    ]
  },
  "output": {
    "publicPath": "/",
    "path": "D:\\vue-work\\reframe-full-stack\\.build\\nodejs",
    "filename": "[name].js",
    "chunkFilename": "[name].js",
    "libraryTarget": "commonjs2"
  },
  "context": "D:\\vue-work\\reframe-full-stack",
  "module": {
    "rules": [
      {
        "use": [
          {
            "loader": "D:\\vue-work\\reframe-full-stack\\node_modules\\babel-loader\\lib\\index.js",
            "options": {
              "presets": [
                [
                  "D:\\vue-work\\reframe-full-stack\\node_modules\\@babel\\preset-env\\lib\\index.js",
                  {
                    "modules": false,
                    "useBuiltIns": "entry",
                    "corejs": 2,
                    "targets": {
                      "node": "8.9.0"
                    }
                  }
                ],
                [
                  "D:\\vue-work\\reframe-full-stack\\node_modules\\@babel\\preset-react\\lib\\index.js"
                ]
              ],
              "plugins": [
                "D:\\vue-work\\reframe-full-stack\\node_modules\\@babel\\plugin-proposal-object-rest-spread\\lib\\index.
js",
                "D:\\vue-work\\reframe-full-stack\\node_modules\\@babel\\plugin-transform-strict-mode\\lib\\index.js"
              ]
            }
          }
        ],
        "exclude": [
          "[RegExp: /node_modules/]"
        ],
        "test": "[RegExp: /\\.js$/]"
      },
      {
        "use": [
          {
            "loader": "D:\\vue-work\\reframe-full-stack\\node_modules\\ignore-loader\\index.js"
          }
        ],
        "test": "[RegExp: /\\.css$/]"
      },
      {
        "use": [
          {
            "loader": "D:\\vue-work\\reframe-full-stack\\node_modules\\@rebuild\\config\\fallback-loader.js",
            "options": {
              "fallback": "D:\\vue-work\\reframe-full-stack\\node_modules\\file-loader\\dist\\cjs.js",
              "name": "[name].hash_[hash].[ext]",
              "emitFile": false
            }
          }
        ]
      },
      {
        "use": [
          {
            "loader": "D:\\vue-work\\reframe-full-stack\\node_modules\\babel-loader\\lib\\index.js",
            "options": {
              "presets": [
                [
                  "D:\\vue-work\\reframe-full-stack\\node_modules\\@babel\\preset-env\\lib\\index.js",
                  {
                    "modules": false,
                    "useBuiltIns": "entry",
                    "corejs": 2,
                    "targets": {
                      "node": "8.9.0"
                    }
                  }
                ],
                [
                  "D:\\vue-work\\reframe-full-stack\\node_modules\\@babel\\preset-react\\lib\\index.js"
                ]
              ],
              "plugins": [
                "D:\\vue-work\\reframe-full-stack\\node_modules\\@babel\\plugin-proposal-object-rest-spread\\lib\\index.
js",
                "D:\\vue-work\\reframe-full-stack\\node_modules\\@babel\\plugin-transform-strict-mode\\lib\\index.js"
              ]
            }
          }
        ],
        "exclude": [
          "[RegExp: /node_modules/]"
        ],
        "test": "[RegExp: /\\.jsx$/]"
      }
    ]
  },
  "devtool": "source-map",
  "mode": "development",
  "target": "node",
  "node": {
    "__dirname": true,
    "__filename": true
  },
  "externals": [
    "[Function: skip_node_modules]"
  ],
  "optimization": {
    "minimize": false
  },
  "resolve": {
    "extensions": [
      ".js",
      ".json",
      ".jsx"
    ]
  }
}
We expect the `context` property of the webpack configuration above to be an absolute path.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

what it means?

thank you

**Comment by brillout** [comment]
Hi @hitmc, it seems to be an issue with Windows. I'll have a deeper look later.

**Comment by brillout** [comment]
Hi @hitmc,

Indeed, it was a windows related issue which is now fixed.

Updating your deps should work:
~~~shell
$ rm yarn.lock && yarn
~~~
Let me know if that works for you.

**Comment by brillout** [comment]
Closing - let me know if you are still having issues and I'll re-open this ticket.
